 const astrologers = [
   {
     name: 'Deepak',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: 'FREE',
     originalPrice: '₹25',
     isFree: true,
     waitTime: null,
     rating: 4.5,
     img: '/one.png',
   },
   {
     name: 'Pushpak',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: 'FREE',
     originalPrice: '₹25',
     isFree: true,
     waitTime: null,
     rating: 4.5,
     img: 'two.png',
   },
   {
     name: 'Tripti',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: '₹5/Min',
     originalPrice: '₹25',
     isFree: false,
     waitTime: null,
     rating: 4.5,
     img: 'three.png',
   },
   {
     name: 'Aarohi',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: '₹25/Min',
     originalPrice: null,
     isFree: false,
     waitTime: null,
     rating: 4.5,
     img: 'four.png',
   },
   {
     name: 'Mahima',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: '₹25/Min',
     originalPrice: null,
     isFree: false,
     waitTime: '7 Min',
     rating: 4.5,
     img: 'five.png',
   },
   {
     name: 'Khushboo',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: '₹25/Min',
     originalPrice: null,
     isFree: false,
     waitTime: '7 Min',
     rating: 4.5,
     img: 'six.png',
   },
   {
     name: 'Aarohi',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: '₹25/Min',
     originalPrice: null,
     isFree: false,
     waitTime: null,
     rating: 4.5,
     img: 'four.png',
   },
   {
     name: 'Mahima',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: '₹25/Min',
     originalPrice: null,
     isFree: false,
     waitTime: '7 Min',
     rating: 4.5,
     img: 'five.png',
   },
   {
     name: 'Khushboo',
     skills: 'Vedic, Numerology...',
     languages: 'Hindi, English, Gujarati',
     experience: '10 Years',
     price: '₹25/Min',
     originalPrice: null,
     isFree: false,
     waitTime: '7 Min',
     rating: 4.5,
     img: 'six.png',
   },
 ];

export default astrologers;